# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
# https://github.com/sebastianbergmann/php-code-coverage/blob/main/.github/workflows/ci.yml

name: PHP Composer

on:
  - pull_request
  - push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          php-version: 8.2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run test suite
        run: composer run-script test

      - name: Run coverage
        run: composer run-script coverage

      - name: Run test suite
        run: composer run-script phpstan
